### ISSUE TITLE
Enhancement: Validator for DNS

### ISSUE THREAD

**Issue by asherlporetz** [insightindustry/validator-collection#16]
https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by insightindustry** [comment]
@asherlporetz Are you looking for validation of domain-name compliant strings? If so, then you can get that using the ``validators.domain()`` function. It should - generally - be compliant with [RFC-1035](https://tools.ietf.org/html/rfc1035), which defines what is valid for DNS.
