### ISSUE TITLE
URL checker does not support private IPs

### ISSUE THREAD

**Issue by fschoenm** [insightindustry/validator-collection#29]
The following URL check fails even though it should be correct:

    is_url('http://127.0.0.1:8443/index.html', allow_special_ips=True)

When using a public IP (e.g. 1.1.1.1), it seems to work.

**Comment by insightindustry** [comment]
This is caused by the same root problem as #28 . Will be fixed in v. 1.3.3.

**Comment by insightindustry** [comment]
Closed in v.1.3.3 by #30
