### ISSUE TITLE
Weird output when using is_url with special IP

### ISSUE THREAD

**Issue by fschoenm** [insightindustry/validator-collection#32]
There is a weird debug output, when a URL with private IP is checked (version 1.3.3):

    >>> from validator_collection.checkers import is_url
    >>> is_url('http://127.0.0.1:8443/index.html', allow_special_ips=True)
    not valid and allowing special ips
    True

**Comment by insightindustry** [comment]
Ack! Looks like an artifact print statement left over from earlier debugging. Thought I'd cleaned them all out. I'll remove it and release a new version momentarily.
