### ISSUE TITLE
Incorrect validation of variable names (and possible vulnerability)

### ISSUE THREAD

**Issue by JordanReiter** [insightindustry/validator-collection#37]
Currently the variable validator actually tries to parse the given string to determine if it's a valid variable name.

What this means is that it actually doesn't answer the question "Is this a valid variable name" but rather, "Does this compile"

Case in point. According to this validator, the following is a valid variable name:

    raise Exception('Foo')\nxyz

To recreate:

```
>>> import validator_collection
>>> invalidVarName='raise Exception("Foo")\nxyz'
>>> validator_collection.is_variable_name(invalidVarName) 
True
>>> 
```

**Comment by insightindustry** [comment]
Thanks for the heads up. I've added regex validation to the `variable_name()` validator and released a new version. 

Still checking compilation as well, but first the code needs to get a full match on a fairly restrictive regex. Hopefully this resolves the issue!
