### ISSUE TITLE
reading the _version.py file in __init__ gives pyinstaller lots of trouble

### ISSUE THREAD

**Issue by eli88fine** [insightindustry/validator-collection#43]
Would you please be able to just import _version instead of opening it as a file?  I'm trying to compile an exe that uses your package and even specifying the _version.py as a hidden import in pyinstaller doesn't help because the __init__.py in your package opens it directly as a file from os.path.direname(__file__).  thanks!

**Comment by insightindustry** [comment]
Sure - let me look into this. I haven't worked with PyInstaller before, so let me experiment with it a bit to see what's the best way to get it working.

**Comment by eli88fine** [comment]
the root of the issue is that it's opening the file instead of importing it.

if you changed _version.py to something like:
VERSION = '1.2.3'

and then in __init__.py did:

from _version import VERSION
__version__=VERSION

then that should be fine
