### ISSUE TITLE
Valid but invalid url

### ISSUE THREAD

**Issue by Tijs-2** [insightindustry/validator-collection#59]
Hi,

I am using your library and I think I found a bug with an url I found on the internet.

To reproduce it I do this:
`
from validator_collection import checkers
print(checkers.is_url("http://www.test.com]"))
`

And then it says True, but I think it should return False

Kind regrards,
Tijs

**Comment by insightindustry** [comment]
Returning `True` for `www.test.com` is actually compliant with [RFC 6761](https://tools.ietf.org/html/rfc6761#section-6.2). As the RFC states for all `*.test.*` URLs:

> 2. Application software SHOULD NOT recognize test names as special, and SHOULD use test names as they would other domain names.
> 
> 3.  Name resolution APIs and libraries SHOULD NOT recognize test names as special and SHOULD NOT treat them differently.  Name resolution APIs SHOULD send queries for test names to their configured caching DNS server(s).
>

**Comment by Tijs-2** [comment]
I think you misread the issue. The issue is not with the test.com because you can replace that with example.com or whatever domain but with the "]" at the end.

If you add one or multiple of them at the and like this the url stays valid:
"http://www.exaple.com]]]]/bla" 

But maybe it is a valid char for a domain name, but I thought it was not allowed as part of the domain name.

**Comment by insightindustry** [comment]
Whoops! Sorry about that, you're absolutely right. I misread the issue and failed to catch the closing square-bracket on the end of the URL. Sorry about that. I'm reopening and will take a look.

**Comment by Tijs-2** [comment]
No problem, glad that I was not mistaken about the character :)

**Comment by insightindustry** [comment]
And yep - this is definitely a bug. The square-bracket is an unsafe character that is not supported in a URL, and it seems that the code is letting it slip through. I'll fix the bug in the next release (I probably won't have a chance to get to it until this weekend, though).

**Comment by Tijs-2** [comment]
I was wondering when the new release with the fix for this issue will be released?
