### ISSUE TITLE
validator_collection could not be resolved

### ISSUE THREAD

**Issue by NSMathpati** [insightindustry/validator-collection#83]
i tried to import the validator collection after installing it in my vscode online through pip install validator_collection.
from validator_collection import validators

email_address = validators.email('test@domain.dev')
print(email_address) 

but when I use it in my code as above I get an error saying . import "validator_collection " could not be resolved.

**Comment by insightindustry** [comment]
Looks like your installation statement is incorrect. It should be: ``pip install validator-collection`` (with a dash, not an underscore).

The rest of your code looks correct.

That should resolve fine for you.

**Comment by NSMathpati** [comment]
ohh Thanks for your help, it works out fine now.Really appreciate your help.
